//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Random_Image.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Random_Image.Resources.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string AdvancedTab {
            get {
                return ResourceManager.GetString("AdvancedTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select advanced options..
        /// </summary>
        public static string AdvancedTabToolTip {
            get {
                return ResourceManager.GetString("AdvancedTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all landscape).
        /// </summary>
        public static string AllLandscapeSuffix {
            get {
                return ResourceManager.GetString("AllLandscapeSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (all portrait).
        /// </summary>
        public static string AllPortraitSuffix {
            get {
                return ResourceManager.GetString("AllPortraitSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated: yes.
        /// </summary>
        public static string AnimatedNoToolTip {
            get {
                return ResourceManager.GetString("AnimatedNoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animated: no.
        /// </summary>
        public static string AnimatedYesToolTip {
            get {
                return ResourceManager.GetString("AnimatedYesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations off.
        /// </summary>
        public static string AnimationsOff {
            get {
                return ResourceManager.GetString("AnimationsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations on.
        /// </summary>
        public static string AnimationsOn {
            get {
                return ResourceManager.GetString("AnimationsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} not installed..
        /// </summary>
        public static string ApplicationNotInstalled {
            get {
                return ResourceManager.GetString("ApplicationNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-scaling:.
        /// </summary>
        public static string AutoScalingLabel {
            get {
                return ResourceManager.GetString("AutoScalingLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-scaling.
        /// </summary>
        public static string AutoScalingTab {
            get {
                return ResourceManager.GetString("AutoScalingTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the auto-scaling mode..
        /// </summary>
        public static string AutoScalingToolTip {
            get {
                return ResourceManager.GetString("AutoScalingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto-scaling when zoomed:.
        /// </summary>
        public static string AutoScalingWhenZoomedLabel {
            get {
                return ResourceManager.GetString("AutoScalingWhenZoomedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Black background.
        /// </summary>
        public static string BlackBackgroundCheckBox {
            get {
                return ResourceManager.GetString("BlackBackgroundCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between black and white backround..
        /// </summary>
        public static string BlackBackgroundToolTip {
            get {
                return ResourceManager.GetString("BlackBackgroundToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current size.
        /// </summary>
        public static string CurrentSizeToolTip {
            get {
                return ResourceManager.GetString("CurrentSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired frame rate:.
        /// </summary>
        public static string DesiredFrameRateLabel {
            get {
                return ResourceManager.GetString("DesiredFrameRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The desired frame rate of all animations.
        /// </summary>
        public static string DesiredFrameRateToolTip {
            get {
                return ResourceManager.GetString("DesiredFrameRateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string DisabledOption {
            get {
                return ResourceManager.GetString("DisabledOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable animations.
        /// </summary>
        public static string EnableAnimationsCheckBox {
            get {
                return ResourceManager.GetString("EnableAnimationsCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch transition animations on and off.
        ///Becomes active when the dialog is closed..
        /// </summary>
        public static string EnableAnimationsToolTip {
            get {
                return ResourceManager.GetString("EnableAnimationsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to display the image on screen!.
        /// </summary>
        public static string FailedToDisplayImage {
            get {
                return ResourceManager.GetString("FailedToDisplayImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the image from file!.
        /// </summary>
        public static string FailedToLoadImage {
            get {
                return ResourceManager.GetString("FailedToLoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File date.
        /// </summary>
        public static string FileDateToolTip {
            get {
                return ResourceManager.GetString("FileDateToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        public static string FileSizeToolTip {
            get {
                return ResourceManager.GetString("FileSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File types:.
        /// </summary>
        public static string FileTypesLabel {
            get {
                return ResourceManager.GetString("FileTypesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file extensions of images to load. The list should be comma-separated..
        /// </summary>
        public static string FileTypesToolTip {
            get {
                return ResourceManager.GetString("FileTypesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to inside edges.
        /// </summary>
        public static string FitInsideEdges {
            get {
                return ResourceManager.GetString("FitInsideEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to inside edges.
        /// </summary>
        public static string FitInsideEdgesRadio {
            get {
                return ResourceManager.GetString("FitInsideEdgesRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the two closer image edges touch the screen box edges.
        ///The visible part of the image content can be aligned with the mouse.
        ///
        ///When activated, you can press the &quot;Forward&quot; or &quot;Back&quot; mouse buttons
        ///to animate alignment of all images..
        /// </summary>
        public static string FitInsideEdgesRadioToolTip {
            get {
                return ResourceManager.GetString("FitInsideEdgesRadioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the two closer image edges touch the screen edges.
        ///The visible part of the image content can be aligned with the mouse..
        /// </summary>
        public static string FitInsideEdgesWhenZoomedRadioToolTip {
            get {
                return ResourceManager.GetString("FitInsideEdgesWhenZoomedRadioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to outside edges.
        /// </summary>
        public static string FitOutsideEdges {
            get {
                return ResourceManager.GetString("FitOutsideEdges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to outside edges.
        /// </summary>
        public static string FitOutsideEdgesRadio {
            get {
                return ResourceManager.GetString("FitOutsideEdgesRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the two more distant image edges touch the screen box edges.
        ///The entire image content is always visible..
        /// </summary>
        public static string FitOutsideEdgesRadioToolTip {
            get {
                return ResourceManager.GetString("FitOutsideEdgesRadioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the two more distant image edges touch the screen edges.
        ///The entire image content is always visible..
        /// </summary>
        public static string FitOutsideEdgesWhenZoomedRadioToolTip {
            get {
                return ResourceManager.GetString("FitOutsideEdgesWhenZoomedRadioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder 1:.
        /// </summary>
        public static string Folder1Label {
            get {
                return ResourceManager.GetString("Folder1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder 2:.
        /// </summary>
        public static string Folder2Label {
            get {
                return ResourceManager.GetString("Folder2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder 3:.
        /// </summary>
        public static string Folder3Label {
            get {
                return ResourceManager.GetString("Folder3Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image folder.
        ///Use the drop down list, or the folder button, or type..
        /// </summary>
        public static string FolderComboTooltip {
            get {
                return ResourceManager.GetString("FolderComboTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FoldersTab {
            get {
                return ResourceManager.GetString("FoldersTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select image folders and extensions..
        /// </summary>
        public static string FoldersTabToolTip {
            get {
                return ResourceManager.GetString("FoldersTabToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full screen.
        /// </summary>
        public static string FullScreenCheckBox {
            get {
                return ResourceManager.GetString("FullScreenCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between full screen and normal screen mode..
        /// </summary>
        public static string FullScreenToolTip {
            get {
                return ResourceManager.GetString("FullScreenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close the dialog.
        /// </summary>
        public static string GoBackButtonTooltip {
            get {
                return ResourceManager.GetString("GoBackButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to images {0} to {1}.
        /// </summary>
        public static string GoBackToImagesToolTip {
            get {
                return ResourceManager.GetString("GoBackToImagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back to image {0}.
        /// </summary>
        public static string GoBackToImageToolTip {
            get {
                return ResourceManager.GetString("GoBackToImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to images {0} to {1}.
        /// </summary>
        public static string GoToImagesToolTip {
            get {
                return ResourceManager.GetString("GoToImagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to image {0}.
        /// </summary>
        public static string GoToImageToolTip {
            get {
                return ResourceManager.GetString("GoToImageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group images.
        /// </summary>
        public static string GroupImagesCheckBox {
            get {
                return ResourceManager.GetString("GroupImagesCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch between grouping images with only the groups being shuffled, and shuffling
        ///all images (if unchecked).
        ///
        ///The option also changes the meaning of the mouse wheel. Switches respectively
        ///between scrolling all images, and scrolling the neighbors of one image (if unchecked).
        ///To scroll all images, use the mouse wheel in the corners of the window..
        /// </summary>
        public static string GroupImagesToolTip {
            get {
                return ResourceManager.GetString("GroupImagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the help dialog.
        /// </summary>
        public static string HelpButtonToolTip {
            get {
                return ResourceManager.GetString("HelpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} image files.
        /// </summary>
        public static string ImageFileCount {
            get {
                return ResourceManager.GetString("ImageFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images:.
        /// </summary>
        public static string ImagesLabel {
            get {
                return ResourceManager.GetString("ImagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string IndexToolTip {
            get {
                return ResourceManager.GetString("IndexToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A.
        /// </summary>
        public static string KeyAnimations {
            get {
                return ResourceManager.GetString("KeyAnimations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B.
        /// </summary>
        public static string KeyBackground {
            get {
                return ResourceManager.GetString("KeyBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O.
        /// </summary>
        public static string KeyGoToRandom {
            get {
                return ResourceManager.GetString("KeyGoToRandom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        public static string KeyMirror {
            get {
                return ResourceManager.GetString("KeyMirror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N.
        /// </summary>
        public static string KeyNormalImages {
            get {
                return ResourceManager.GetString("KeyNormalImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        public static string KeyPauseResume {
            get {
                return ResourceManager.GetString("KeyPauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L.
        /// </summary>
        public static string KeyRotateLeft {
            get {
                return ResourceManager.GetString("KeyRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string KeyRotateRight {
            get {
                return ResourceManager.GetString("KeyRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U.
        /// </summary>
        public static string KeyUpsideDown {
            get {
                return ResourceManager.GetString("KeyUpsideDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout {0} × {1}.
        /// </summary>
        public static string LayoutDimensions {
            get {
                return ResourceManager.GetString("LayoutDimensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        public static string LayoutTab {
            get {
                return ResourceManager.GetString("LayoutTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the arrangement and number of visible images..
        /// </summary>
        public static string LayoutToolTip {
            get {
                return ResourceManager.GetString("LayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded size.
        /// </summary>
        public static string LoadedSizeToolTip {
            get {
                return ResourceManager.GetString("LoadedSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading image files....
        /// </summary>
        public static string LoadingImageFiles {
            get {
                return ResourceManager.GetString("LoadingImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading in progress....
        /// </summary>
        public static string LoadingInProgress {
            get {
                return ResourceManager.GetString("LoadingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image dimensions limit:.
        /// </summary>
        public static string MaxPixelResolutionLabel {
            get {
                return ResourceManager.GetString("MaxPixelResolutionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When loading images, any bitmaps with either width or height exceeding this value
        ///will be scaled down to enhance performance..
        /// </summary>
        public static string MaxPixelResolutionToolTip {
            get {
                return ResourceManager.GetString("MaxPixelResolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mirror.
        /// </summary>
        public static string MirrorToolTip {
            get {
                return ResourceManager.GetString("MirrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miscellaneous.
        /// </summary>
        public static string MiscellaneousTab {
            get {
                return ResourceManager.GetString("MiscellaneousTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select miscellaneous options..
        /// </summary>
        public static string MiscellaneousToolTip {
            get {
                return ResourceManager.GetString("MiscellaneousToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbor.
        /// </summary>
        public static string NeighborToolTip {
            get {
                return ResourceManager.GetString("NeighborToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image files found.
        /// </summary>
        public static string NoImagesFound {
            get {
                return ResourceManager.GetString("NoImagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal image.
        /// </summary>
        public static string NormalImage {
            get {
                return ResourceManager.GetString("NormalImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal images.
        /// </summary>
        public static string NormalImages {
            get {
                return ResourceManager.GetString("NormalImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the folder selection dialog..
        /// </summary>
        public static string OpenFolderSelectionToolTip {
            get {
                return ResourceManager.GetString("OpenFolderSelectionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the options dialog.
        /// </summary>
        public static string OptionsButtonToolTip {
            get {
                return ResourceManager.GetString("OptionsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        public static string OriginalSize {
            get {
                return ResourceManager.GetString("OriginalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        public static string OriginalSizeRadio {
            get {
                return ResourceManager.GetString("OriginalSizeRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable auto-scaling and use the original image dimensions.
        ///The visible part of the image content can be aligned with the mouse
        ///if the image is larger than the screen..
        /// </summary>
        public static string OriginalSizeRadioToolTip {
            get {
                return ResourceManager.GetString("OriginalSizeRadioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original size.
        /// </summary>
        public static string OriginalSizeToolTip {
            get {
                return ResourceManager.GetString("OriginalSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To optimize performance, it is recommended to close all other applications extensively utilizing
        ///the graphics card, such as web browsers..
        /// </summary>
        public static string PerformanceTipLabel {
            get {
                return ResourceManager.GetString("PerformanceTipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group images.
        /// </summary>
        public static string RandomGroupOrder {
            get {
                return ResourceManager.GetString("RandomGroupOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random order.
        /// </summary>
        public static string RandomOrder {
            get {
                return ResourceManager.GetString("RandomOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart every N images:.
        /// </summary>
        public static string RestartEveryNImagesLabel {
            get {
                return ResourceManager.GetString("RestartEveryNImagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart after showing the selected number of images to remedy the problem
        ///of stuttering animations. To restart immediately, press F4 after closing this dialog..
        /// </summary>
        public static string RestartEveryNImagesTooltip {
            get {
                return ResourceManager.GetString("RestartEveryNImagesTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left.
        /// </summary>
        public static string RotateLeft {
            get {
                return ResourceManager.GetString("RotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left.
        /// </summary>
        public static string RotateLeftToolTip {
            get {
                return ResourceManager.GetString("RotateLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right.
        /// </summary>
        public static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right.
        /// </summary>
        public static string RotateRightToolTip {
            get {
                return ResourceManager.GetString("RotateRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as default.
        /// </summary>
        public static string SaveAsDefaultButton {
            get {
                return ResourceManager.GetString("SaveAsDefaultButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes as default settings in the configuration file.
        /// </summary>
        public static string SaveAsDefaultButtonTooltip {
            get {
                return ResourceManager.GetString("SaveAsDefaultButtonTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a folder with images by
        ///pressing F2, or add more folders in the
        ///&quot;{0}&quot; dialog by pressing F10..
        /// </summary>
        public static string SelectAFolderOrUseOptions {
            get {
                return ResourceManager.GetString("SelectAFolderOrUseOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not exist:.
        /// </summary>
        public static string TheFileDoesNotExist {
            get {
                return ResourceManager.GetString("TheFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        public static string Thumbnails {
            get {
                return ResourceManager.GetString("Thumbnails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thumbnails.
        /// </summary>
        public static string ThumbnailsRadio {
            get {
                return ResourceManager.GetString("ThumbnailsRadio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make the two closer image edges touch the screen box edges.
        ///Images have rounded corners, are always centered and cannot be aligned with the mouse..
        /// </summary>
        public static string ThumbnailsRadioToolTip {
            get {
                return ResourceManager.GetString("ThumbnailsRadioToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        public static string TipLabel {
            get {
                return ResourceManager.GetString("TipLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upside-down.
        /// </summary>
        public static string UpsideDownImage {
            get {
                return ResourceManager.GetString("UpsideDownImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upside-down.
        /// </summary>
        public static string UpsideDownToolTip {
            get {
                return ResourceManager.GetString("UpsideDownToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string ZoomToolTip {
            get {
                return ResourceManager.GetString("ZoomToolTip", resourceCulture);
            }
        }
    }
}
